### ISSUE TITLE
Timestamps in logs

### ISSUE THREAD

**Issue by vmx** [ipfs/jenkins#98]
It would be useful to have timestamps on every line of the logs. IIRC there's a Jenkins plugin for that.

**Comment by victorb** [comment]
So, this is seemingly easy to add for the old console output but seems to not be supported for the blue ocean UI.

With that said, each command that is executed and visible in blue ocean, shows the time taken on the right side. Is this helpful? Then you can at least see how long time each command takes.

Otherwise we can always wrap every command in `ts` from moreutils, but have to figure out how to get the same for windows and might impact performance somewhat as well.

What's the main usecase of seeing the timestamps? Ignoring the fact that we can already see how long time each command takes.

**Comment by victorb** [comment]
Relevant issues from Jenkins issue tracker:

- https://issues.jenkins-ci.org/browse/JENKINS-43107
- https://issues.jenkins-ci.org/browse/JENKINS-44195

**Comment by ghost** [comment]
If the workers are ubuntu, we could install the `devscripts` package and use its `annotate-output` tool, e.g. `annotate-output sh -c 'make build && make test'`

**Comment by victorb** [comment]
`ts` is probably already installed anyways, and we also have windows + macos workers... Let's figure out the use case, then solutions :) But thanks for the recommendation anyways

**Comment by vmx** [comment]
@VictorBjelkholm My main sue case is having a test that times out. I then add log commands to see where the time is actually spent. If every log line contains a timestamp, it's easy to see that. I'm happy to have that only on the old UI as I can switch to if if I really need to see the timestamps.

**Comment by victorb** [comment]
Moved to https://github.com/ipfs/testing/issues/106
