### ISSUE TITLE
Previous jobs are not cancelled

### ISSUE THREAD

**Issue by vmx** [ipfs/jenkins#99]
If another job is triggered and other ones on the same PR are still in the queue, those old outdated ones are not cancelled, but also run. This jams up Jenkins more then necessary.

**Comment by victorb** [comment]
Thanks. Supposedly, it cancels previous builds if a new commit is made to a PR but seems like it's currently not working. Will look into it as this will degrade jenkins performance significantly.

**Comment by alanshaw** [comment]
+1 on this - also smarts for not building the same commit if one is already running unless it was user requested. I'm also getting a double build for the same commit as I often push a branch and then immediately open a PR.

I can open a separate issue if you want @VictorBjelkholm?

**Comment by victorb** [comment]
@alanshaw no, think is fine.

Regarding double builds, idea was that branches would be tested in isolation and PRs are tested as they are merged into master, but since we almost never push branches without opening PRs, it might be better to just skip the builds that happens on branches, only do PR builds.

**Comment by victorb** [comment]
This issue was moved to ipfs/testing#109
